site_name: R与Python的阵营之争
site_author: 徐静
site_favicon: icon.ico
repo_url: https://github.com/DataXujing/RVSPython2.0/
pages:
  - 主页: index.md
  - 数据科学中的R与Python: chapter1.md
  - 机器学习: chapter2.md
  - 深度学习与生成学习: chapter3.md
  - 网络爬虫: chapter4.md
  - 数据库交互: chapter5.md
  - ‘造轮子’: chapter6.md
  - GUI开发: chapter7.md
  - Web开发: chapter8.md
  - R与Python的相互调用: chapter9.md
  - R、Python与大数据: chapter10.md
  - 其他: chapter11.md
  - 关于: about.md
theme: readthedocs





